# Generated by Django 2.2 on 2019-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('C', 'C'), ('C#', 'C#'), ('C++', 'C++'), ('PHP', 'PHP'), ('JAVA', 'JAVA'), ('PYTHON', 'PYTHON')], default='C', max_length=50)),
            ],
        ),
    ]
